board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('', views.index, name='index'),
    path('list/', views.list, name='list'),
    path('read/<int:id>/', views.read, name='read'),
    path('regist/', views.regist, name='regist'),
    path('edit/<int:id>/', views.edit, name='edit'),
    path('remove/<int:id>/', views.remove, name='remove')

]

djangoProject0323/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls'))
]

board/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Board(models.Model):
    title = models.CharField(max_length=50)
    writer = models.CharField(max_length=30)
    content = models.TextField()
    regdate = models.DateTimeField(auto_now=timezone.now)
    readcount = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.title}, {self.writer}, {self.readcount}"

    def incrementReadCount(self):
        self.readcount += 1
        self.save()

board/views.py
from django.shortcuts import render, redirect, reverse
from .models import Board

# Create your views here.

def index(request):
    return render(request, 'board/index.html')

def list(request):
    board_list = Board.objects.all().order_by('-id')
    context = {
        'board_list': board_list,
    }
    return render(
        request,
        'board/list.html',
        context
    )

def read(request, id):
    board = Board.objects.get(pk=id)
    board.incrementReadCount()
    return render(request, 'board/read.html', {'board':board})

def regist(request):
    if request.method == 'POST':
        title = request.POST['title']
        writer = request.POST.get('writer')
        content = request.POST['content']
        Board(title=title, writer=writer, content=content).save()
        return redirect(reverse('board:list'))
    else:
        return render(request, 'board/regist.html')

def edit(request, id):
    board = Board.objects.get(pk=id)
    if request.method == 'POST':
        board.title = request.POST['title']
        board.writer = request.POST.get('writer', 'default')
        board.content = request.POST['content']
        board.save()
        return redirect(reverse('board:read', args=(id,)))
    else:
        return render(request, 'board/edit.html', {'board':board})

def remove(request, id):
    board = Board.objects.get(pk=id)
    if request.method == 'POST':
        board.delete()
        return redirect(reverse('board:list'))
    else:
        return render(request, 'board/remove.html', {'board':board})

board/templates/board/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% block content %}{% endblock %}
</body>
</html>

board/templates/board/edit.html
{% extends 'board/base.html' %}
{% block title %}수정{% endblock %}
{% block content %}
	<form method="post">
        {% csrf_token %}
        <input type="hidden" name="writer" value="{{ board.writer }}">
    <table border="1">
        <tr>
            <th>Title</th>
            <td>
                <input type="text" name="title" value="{{ board.title }}">
            </td>
        </tr>
        <tr>
            <th>Writer</th>
            <td>
                <input type="text" name="writer" value="{{ board.writer }}" disabled>
            </td>
        </tr>
        <tr>
            <th>Content</th>
            <td>
                <textarea name="content">{{ board.content }}</textarea>
            </td>
        </tr>
    </table>
    <button type="submit">수정</button>
    </form>
{% endblock %}

board/templates/board/index.html
{% extends 'board/base.html' %}
{% block title %}Index{% endblock %}
{% block content %}
    <ul>
        <li><a href="{% url 'board:list' %}">목록</a></li>
        <li><a href="{% url 'board:regist' %}">등록</a></li>
    </ul>
{% endblock %}

board/templates/board/list.html
{% extends 'board/base.html' %}
{% block title %}목록{% endblock %}
{% block content %}
{% if board_list %}
    <table border="1">
        <tr>
            <th>번호</th>
            <th>제목</th>
            <th>작성자</th>
            <th>조회수</th>
        </tr>
    {% for board in board_list %}
        <tr>
            <td>{{ board.id }}</td>
            <td><a href="{% url 'board:read' board.id %}">{{ board.title }}</a></td>
            <td>{{ board.writer }}</td>
            <td>{{ board.readcount }}</td>
        </tr>
    {% endfor %}
    </table>
{% else %}
    게시글이 존재하지 않습니다.
{% endif %}
<a href="{% url 'board:regist' %}"><button>등록</button></a>
{% endblock %}

board/templates/board/read.html
{% extends 'board/base.html' %}
{% block title %}내용{% endblock %}
{% block content %}
<table border="1">
    <tr>
        <th>등록일</th>
        <th>조회수</th>
    </tr>
    <tr>
        <td>{{ board.regdate }}</td>
        <td>{{ board.readcount }}</td>
    </tr>
    <tr>
        <th>제목</th>
        <td>{{ board.title }}</td>
    </tr>
    <tr>
        <th>작성자</th>
        <td>{{ board.writer }}</td>
    </tr>
    <tr>
        <th>내용</th>
        <td>{{ board.content }}</td>
    </tr>
</table>
<a href="{% url 'board:edit' board.id %}"><button>수정</button></a>
<a href="{% url 'board:remove' board.id %}"><button>삭제</button></a>
<a href="{% url 'board:list' %}"><button>목록</button></a>
{% endblock %}

board/templates/board/regist.html
{% extends 'board/base.html' %}
{% block title %}등록{% endblock %}
{% block content %}
	<form method="post">
    {% csrf_token %}
    <table border="1">
        <tr>
            <th>Title</th>
            <td>
                <input type="text" name="title">
            </td>
        </tr>
        <tr>
            <th>Writer</th>
            <td>
                <input type="text" name="writer">
            </td>
        </tr>
        <tr>
            <th>Content</th>
            <td>
                <textarea name="content"></textarea>
            </td>
        </tr>
    </table>
    <button type="submit">등록</button>
    </form>
{% endblock %}

board/templates/board/remove.html
{% extends 'board/base.html' %}
{% block title %}삭제{% endblock %}
{% block content %}
	<form method="post">
        {% csrf_token %}
        {{ board.writer }}가 작성한 게시글을 삭제하시겠습니까? <button type="submit">예</button>
    </form>
{% endblock %}